### ISSUE TITLE
runSnobotSim doesn't work

### ISSUE THREAD

**Issue by orel-david** [snobotsim/SnobotSim#58]
**Describe the bug**
task "runSnobotSim" doesn't work

**Quick Glance Configuration**
Please provide the following information
1. SnobotSimPlugin version-2019-0.2.0
2. SnobotSim version-2019-0.2.0
3. GradleRIO version-2019.1.1
4. Your Operating System.  widows 10

**To Reproduce**
Please information on when the issue occurs, and/or what you did to cause the issue to surface. i.e.
- Does the issue happen during compilation (`gradlew build`)no
- Does the issue happen when simulating from the command line (`gradlew runSnobotSim`)yes
- Does the issue happen on startup (unsatisfied link, class not found, NPE, etc) haven't got there
- Does the issue happen while running (When we try to use a joystick..., when we put it in auton..., etc)haven't got there

**Expected behavior**
expected to run the task

**Detailed Setup**
```
    plugins {
        id 'java'
        id 'idea'
        id "edu.wpi.first.GradleRIO" version "2019.1.1"
        id "com.snobot.simulator.plugin.SnobotSimulatorPlugin" version "2019-0.2.0" apply false
}
    group 'Robot'
    version '1.0'

    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    def includeDesktopSupport = true
        apply plugin: com.snobot.simulator.plugin.SnobotSimulatorPlugin
        configurations {
        snobotSimCompile
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        compile wpi.deps.wpilib()
        compile wpi.deps.vendor.java()

        nativeZip wpi.deps.vendor.jni(wpi.platforms.roborio)
        nativeDesktopZip wpi.deps.vendor.jni(wpi.platforms.desktop)
        testCompile 'junit:junit:4.12'
        
        snobotSimCompile snobotSimJava()
        
    }

    def ROBOT_CLASS = "robot.Robot"

    deploy {
        targets {
            target("roborio", edu.wpi.first.gradlerio.frc.RoboRIO) {
                team = getTeamOrDefault()
            }
        }
        artifacts {
            artifact('frcJava', edu.wpi.first.gradlerio.frc.FRCJavaArtifact) {
                targets << "roborio"
            }
        }
    }

    task wrapper(type: Wrapper) {
        gradleVersion = '4.9' 
    }

    compileJava {
        classpath = sourceSets.main.compileClasspath
        options.encoding = 'UTF-8'
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }

    jar {
        from configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
        manifest edu.wpi.first.gradlerio.GradleRIOPlugin.javaManifest(ROBOT_CLASS)
    }
```

**Additional context**
stacktrace:
```
.\gradlew build --stacktrace
Warning! Your wrapper zip / dist store is set to wrapper/dists!
This can cause issues when going to competition, since this directory is automatically purged once a month
Run ./gradlew wrapper to fix this, or use -Pskip-inspector-wrapper to squash this warning.
> Task :extractSnobotSimJavaJNI FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extractSnobotSimJavaJNI'.
>org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(Ljava/lang/Iterable;Lgroovy/lang/Closure;)Ljava/util/List;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':extractSnobotSimJavaJNI'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:273)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:258)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoSuchMethodError: org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(Ljava/lang/Iterable;Lgroovy/lang/Closure;)Ljava/util/List;
        at com.snobot.simulator.plugin.BaseExtractSnobotSimNatives$_runExtract_closure2$_closure4.doCall(BaseExtractSnobotSimNatives.groovy:37)
        at com.snobot.simulator.plugin.BaseExtractSnobotSimNatives$_runExtract_closure2$_closure4.call(BaseExtractSnobotSimNatives.groovy)
        at com.snobot.simulator.plugin.BaseExtractSnobotSimNatives$_runExtract_closure2.doCall(BaseExtractSnobotSimNatives.groovy:34)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:174)
        at com.snobot.simulator.plugin.BaseExtractSnobotSimNatives.runExtract(BaseExtractSnobotSimNatives.groovy:31)
        at com.snobot.simulator.plugin.java_sim.ExtractSnobotSimJavaNatives.extract(ExtractSnobotSimJavaNatives.groovy:21)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:786)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:753)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
2 actionable tasks: 1 executed, 1 up-to-date
```

**Comment by pjreiniger** [comment]
Thats odd. Try upgrading your gradle wrapper to 5.0. That is what comes with the WPI project set up, and what I've tested the examples with

// build.gradle
```
    task wrapper(type: Wrapper) {
        gradleVersion = '5.0' 
    }
```

// command line
`gradlew wrapper`

**Comment by orel-david** [comment]
now i get this:
```
> Task :runJavaSnobotSim FAILED
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/snobot/simulator/ctre/CtreCallback has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versi
ons up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at com.snobot.simulator.JniLibraryResourceLoader.loadLibrary(JniLibraryResourceLoader.java:77)
        at com.snobot.simulator.jni.BaseSnobotJni.<clinit>(BaseSnobotJni.java:16)
        at com.snobot.simulator.wrapper_accessors.java.JavaDataAccessor.<init>(JavaDataAccessor.java:40)
        at com.snobot.simulator.DefaultDataAccessorFactory.initalize(DefaultDataAccessorFactory.java:25)
        at com.snobot.simulator.Main.main(Main.java:28)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runJavaSnobotSim'.
> Process 'command 'java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 30s
4 actionable tasks: 4 executed
```

**Comment by pjreiniger** [comment]
If you are running from the command line you need to make sure JAVA_HOME points to jdk11. If you open it from the vscode terminal it should be set already

**Comment by pjreiniger** [comment]
See new documentation for 2020

https://snobotsimdocs.readthedocs.io/en/latest/index.html
